<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-JobEngine.Worker-8c4b5db6-66d4-492e-9d04-5e1d48521be2</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EFCore.NamingConventions"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting"/>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JobEngine.Core\JobEngine.Core.csproj" />
    <ProjectReference Include="..\JobEngine.Persistence\JobEngine.Persistence.csproj" />
  </ItemGroup>
</Project>
